"""Delta-space skew metrics — synthetic chains only, no Kite, no fixtures on disk.

Every chain here is generated by pricing a known vol curve with Black-76, so the
tests assert that the module *recovers what was put in*: the forward, the vol at
each strike, and the resulting risk reversal.
"""

from __future__ import annotations

import math

import pytest
from vollib.black import black

from options.skew_metrics import (
    black76_delta,
    black76_iv,
    build_skew,
    forward_from_chain,
    implied_forward,
    iv_at_abs_delta,
    otm_wings,
)

R = 0.065
T = 30 / 365.0
FORWARD = 24_500.0
STEP = 50.0


def make_chain(
    forward: float = FORWARD,
    *,
    vol_at=lambda k, f: 0.12,
    width: int = 25,
    step: float = STEP,
    strikes: list[float] | None = None,
    tte: float = T,
) -> dict[float, dict[str, float | None]]:
    """Price a full CE/PE chain off ``forward`` using ``vol_at(strike, forward)``."""
    atm = round(forward / step) * step
    ks = strikes if strikes is not None else [atm + i * step for i in range(-width, width + 1)]
    chain: dict[float, dict[str, float | None]] = {}
    for k in ks:
        sigma = vol_at(k, forward)
        chain[float(k)] = {
            "CE": black("c", forward, k, tte, R, sigma),
            "PE": black("p", forward, k, tte, R, sigma),
        }
    return chain


def skewed(slope: float):
    """Linear vol-vs-log-moneyness curve. ``slope`` > 0 makes puts richer."""
    return lambda k, f: 0.12 + slope * math.log(f / k)


# --- forward recovery -------------------------------------------------------


def test_implied_forward_recovers_forward_exactly():
    chain = make_chain()
    k = 24_500.0
    got = implied_forward(k, chain[k]["CE"], chain[k]["PE"], T, R)
    assert got == pytest.approx(FORWARD, abs=0.01)


def test_forward_recovered_even_when_reference_is_spot():
    """The reference only picks strikes; a wrong reference must not move F.

    This is the bug the module exists to remove: spot sits ~100 points below the
    forward at 30 DTE, and pricing off spot is what produced the parity gap that
    flipped the sign of the risk reversal.
    """
    chain = make_chain()
    spot = FORWARD - 100.0
    out = forward_from_chain(chain, spot, T, R)
    assert out["forward"] == pytest.approx(FORWARD, abs=0.05)
    assert out["basis"] == pytest.approx(100.0, abs=0.05)
    assert out["spread"] == pytest.approx(0.0, abs=0.05)
    assert len(out["strikes_used"]) == 3


def test_forward_unavailable_without_a_complete_pair():
    chain = {24_500.0: {"CE": 100.0, "PE": None}, 24_550.0: {"CE": 80.0, "PE": None}}
    assert forward_from_chain(chain, 24_500.0, T, R)["forward"] is None


def test_one_stale_leg_does_not_move_the_forward():
    """Median over three near-ATM strikes absorbs a single bad quote."""
    chain = make_chain()
    chain[24_500.0]["CE"] = chain[24_500.0]["CE"] * 3  # stale/crossed print
    out = forward_from_chain(chain, FORWARD, T, R)
    assert out["forward"] == pytest.approx(FORWARD, abs=0.05)
    assert out["spread"] > 100  # but the disagreement is reported, not hidden


# --- IV / delta round trips -------------------------------------------------


def test_black76_iv_round_trip():
    price = black("c", FORWARD, 24_800.0, T, R, 0.137)
    assert black76_iv(price, FORWARD, 24_800.0, T, "CE", R) == pytest.approx(0.137, abs=1e-6)


@pytest.mark.parametrize("bad", [None, 0.0, -5.0])
def test_black76_iv_rejects_unusable_prices(bad):
    assert black76_iv(bad, FORWARD, 24_800.0, T, "CE", R) is None


def test_atm_delta_is_about_half():
    d = black76_delta(FORWARD, FORWARD, T, 0.12, "CE", R)
    assert d == pytest.approx(0.5, abs=0.02)


# --- wings and interpolation ------------------------------------------------


def test_wings_are_otm_only_and_split_at_the_forward():
    calls, puts = otm_wings(make_chain(), FORWARD, T, R)
    assert all(p.strike >= FORWARD and p.option_type == "CE" for p in calls)
    assert all(p.strike < FORWARD and p.option_type == "PE" for p in puts)
    assert calls and puts


def test_flat_vol_recovers_flat_vol_on_both_wings():
    calls, puts = otm_wings(make_chain(), FORWARD, T, R)
    for p in calls + puts:
        assert p.iv == pytest.approx(0.12, abs=1e-4)


def test_iv_at_delta_interpolates_within_the_observed_range():
    calls, _ = otm_wings(make_chain(vol_at=skewed(0.5)), FORWARD, T, R)
    q = iv_at_abs_delta(calls, 0.25)
    assert q.quality == "interpolated"
    lo = min(p.iv for p in calls)
    hi = max(p.iv for p in calls)
    assert lo <= q.iv <= hi


def test_iv_at_delta_flags_extrapolation_instead_of_projecting():
    """A window that never reaches 25Δ must say so — not invent a wing."""
    narrow = make_chain(width=2)  # ATM +/- 2 strikes: deepest call is ~40 delta
    calls, _ = otm_wings(narrow, FORWARD, T, R)
    q = iv_at_abs_delta(calls, 0.25)
    assert q.quality == "extrapolated"
    assert q.nearest_abs_delta > 0.25
    assert q.iv == pytest.approx(min(p.iv for p in calls), abs=1e-9)


def test_iv_at_delta_unavailable_on_an_empty_wing():
    q = iv_at_abs_delta([], 0.25)
    assert q == (None, "unavailable", None, 0, None)


def test_bracket_gap_reports_how_sparse_the_wing_was():
    """A dense wing brackets 25Δ tightly; a sparse one spans a wide delta range."""
    dense, _ = otm_wings(make_chain(), FORWARD, T, R)
    sparse, _ = otm_wings(
        make_chain(strikes=[FORWARD - 500, FORWARD, FORWARD + 1500]), FORWARD, T, R
    )
    assert iv_at_abs_delta(dense, 0.25).bracket_gap < 0.10
    assert iv_at_abs_delta(sparse, 0.25).bracket_gap > 0.30


# --- the headline metrics ---------------------------------------------------


def test_flat_smile_has_zero_risk_reversal_and_zero_butterfly():
    out = build_skew(make_chain(), FORWARD, T)
    assert out["ok"]
    assert out["risk_reversal"] == pytest.approx(0.0, abs=1e-4)
    assert out["butterfly"] == pytest.approx(0.0, abs=1e-4)
    assert out["quality"] == "interpolated"


def test_put_skew_gives_a_negative_risk_reversal():
    """Richer puts -> RR < 0. The defensive equity skew."""
    out = build_skew(make_chain(vol_at=skewed(0.5)), FORWARD, T)
    assert out["risk_reversal"] < 0
    assert out["put_wing"]["iv"] > out["call_wing"]["iv"]


def test_call_skew_gives_a_positive_risk_reversal():
    out = build_skew(make_chain(vol_at=skewed(-0.5)), FORWARD, T)
    assert out["risk_reversal"] > 0
    assert out["call_wing"]["iv"] > out["put_wing"]["iv"]


def test_risk_reversal_magnitude_tracks_the_input_skew():
    """RR is the vol difference between the two 25Δ strikes, so it should equal
    the input curve evaluated at those strikes."""
    out = build_skew(make_chain(vol_at=skewed(0.5)), FORWARD, T)
    calls, puts = otm_wings(make_chain(vol_at=skewed(0.5)), FORWARD, T, R)
    c25 = iv_at_abs_delta(calls, 0.25).iv
    p25 = iv_at_abs_delta(puts, 0.25).iv
    assert out["risk_reversal"] == pytest.approx(c25 - p25, abs=1e-9)


def test_smile_gives_a_positive_butterfly():
    """Both wings above ATM -> positive fly, the tail-convexity bid."""
    out = build_skew(make_chain(vol_at=lambda k, f: 0.12 + 3.0 * math.log(f / k) ** 2), FORWARD, T)
    assert out["butterfly"] > 0
    assert out["risk_reversal"] == pytest.approx(0.0, abs=0.01)


def test_atm_parity_gap_is_zero_on_a_correct_forward():
    """The module's own correctness check: one strike, one implied vol.

    Regression guard for the spot-vs-forward bug — pricing this same chain off
    spot opens a gap of roughly a vol point in each direction.
    """
    out = build_skew(make_chain(), FORWARD - 100.0, T)
    assert out["atm"]["parity_gap"] == pytest.approx(0.0, abs=1e-4)
    assert out["atm"]["iv"] == pytest.approx(0.12, abs=1e-4)


def test_narrow_window_reports_extrapolated_quality():
    out = build_skew(make_chain(width=2), FORWARD, T)
    assert out["ok"]
    assert out["quality"] == "extrapolated"


def test_build_skew_fails_loudly_without_a_forward():
    out = build_skew({24_500.0: {"CE": 100.0, "PE": None}}, 24_500.0, T)
    assert out["ok"] is False
    assert "forward" in out["error"]


def test_points_are_sorted_by_strike_for_charting():
    out = build_skew(make_chain(vol_at=skewed(0.5)), FORWARD, T)
    strikes = [p["strike"] for p in out["points"]]
    assert strikes == sorted(strikes)
    assert len(strikes) == len(out["points"])


# --- MCX shape: wide strikes, high vol, sparse quotes ------------------------


def test_mcx_style_chain_resolves():
    """CRUDEOIL-shaped: ~8000 level, 50-point strikes, ~40% vol, thin wings.

    MCX options are options *on futures*, so parity recovers that contract
    month's future directly and the basis against the front-month reference is
    expected to be non-zero rather than an error.
    """
    fwd = 8_050.0
    chain = make_chain(forward=fwd, vol_at=lambda k, f: 0.40 + 0.6 * math.log(f / k), width=20)
    for k in list(chain)[:3]:  # deep wing with no two-sided market
        chain[k] = {"CE": None, "PE": None}
    out = build_skew(chain, 7_991.0, T)
    assert out["ok"]
    assert out["forward"] == pytest.approx(fwd, abs=0.5)
    assert out["forward_basis"] == pytest.approx(59.0, abs=1.0)
    assert out["risk_reversal"] < 0
