/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WaveRouteImport } from './routes/wave'
import { Route as SurvivorRouteImport } from './routes/survivor'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RollingStraddleRouteImport } from './routes/rolling-straddle'
import { Route as OiVarRouteImport } from './routes/oi-var'
import { Route as OiTrackerRouteImport } from './routes/oi-tracker'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LiveRouteImport } from './routes/live'
import { Route as ExecutionRouteImport } from './routes/execution'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BacktestRouteImport } from './routes/backtest'
import { Route as IndexRouteImport } from './routes/index'

const WaveRoute = WaveRouteImport.update({
  id: '/wave',
  path: '/wave',
  getParentRoute: () => rootRouteImport,
} as any)
const SurvivorRoute = SurvivorRouteImport.update({
  id: '/survivor',
  path: '/survivor',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RollingStraddleRoute = RollingStraddleRouteImport.update({
  id: '/rolling-straddle',
  path: '/rolling-straddle',
  getParentRoute: () => rootRouteImport,
} as any)
const OiVarRoute = OiVarRouteImport.update({
  id: '/oi-var',
  path: '/oi-var',
  getParentRoute: () => rootRouteImport,
} as any)
const OiTrackerRoute = OiTrackerRouteImport.update({
  id: '/oi-tracker',
  path: '/oi-tracker',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const ExecutionRoute = ExecutionRouteImport.update({
  id: '/execution',
  path: '/execution',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BacktestRoute = BacktestRouteImport.update({
  id: '/backtest',
  path: '/backtest',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/backtest': typeof BacktestRoute
  '/dashboard': typeof DashboardRoute
  '/execution': typeof ExecutionRoute
  '/live': typeof LiveRoute
  '/login': typeof LoginRoute
  '/oi-tracker': typeof OiTrackerRoute
  '/oi-var': typeof OiVarRoute
  '/rolling-straddle': typeof RollingStraddleRoute
  '/settings': typeof SettingsRoute
  '/survivor': typeof SurvivorRoute
  '/wave': typeof WaveRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/backtest': typeof BacktestRoute
  '/dashboard': typeof DashboardRoute
  '/execution': typeof ExecutionRoute
  '/live': typeof LiveRoute
  '/login': typeof LoginRoute
  '/oi-tracker': typeof OiTrackerRoute
  '/oi-var': typeof OiVarRoute
  '/rolling-straddle': typeof RollingStraddleRoute
  '/settings': typeof SettingsRoute
  '/survivor': typeof SurvivorRoute
  '/wave': typeof WaveRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/backtest': typeof BacktestRoute
  '/dashboard': typeof DashboardRoute
  '/execution': typeof ExecutionRoute
  '/live': typeof LiveRoute
  '/login': typeof LoginRoute
  '/oi-tracker': typeof OiTrackerRoute
  '/oi-var': typeof OiVarRoute
  '/rolling-straddle': typeof RollingStraddleRoute
  '/settings': typeof SettingsRoute
  '/survivor': typeof SurvivorRoute
  '/wave': typeof WaveRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/backtest'
    | '/dashboard'
    | '/execution'
    | '/live'
    | '/login'
    | '/oi-tracker'
    | '/oi-var'
    | '/rolling-straddle'
    | '/settings'
    | '/survivor'
    | '/wave'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/backtest'
    | '/dashboard'
    | '/execution'
    | '/live'
    | '/login'
    | '/oi-tracker'
    | '/oi-var'
    | '/rolling-straddle'
    | '/settings'
    | '/survivor'
    | '/wave'
  id:
    | '__root__'
    | '/'
    | '/backtest'
    | '/dashboard'
    | '/execution'
    | '/live'
    | '/login'
    | '/oi-tracker'
    | '/oi-var'
    | '/rolling-straddle'
    | '/settings'
    | '/survivor'
    | '/wave'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BacktestRoute: typeof BacktestRoute
  DashboardRoute: typeof DashboardRoute
  ExecutionRoute: typeof ExecutionRoute
  LiveRoute: typeof LiveRoute
  LoginRoute: typeof LoginRoute
  OiTrackerRoute: typeof OiTrackerRoute
  OiVarRoute: typeof OiVarRoute
  RollingStraddleRoute: typeof RollingStraddleRoute
  SettingsRoute: typeof SettingsRoute
  SurvivorRoute: typeof SurvivorRoute
  WaveRoute: typeof WaveRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wave': {
      id: '/wave'
      path: '/wave'
      fullPath: '/wave'
      preLoaderRoute: typeof WaveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/survivor': {
      id: '/survivor'
      path: '/survivor'
      fullPath: '/survivor'
      preLoaderRoute: typeof SurvivorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rolling-straddle': {
      id: '/rolling-straddle'
      path: '/rolling-straddle'
      fullPath: '/rolling-straddle'
      preLoaderRoute: typeof RollingStraddleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oi-var': {
      id: '/oi-var'
      path: '/oi-var'
      fullPath: '/oi-var'
      preLoaderRoute: typeof OiVarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oi-tracker': {
      id: '/oi-tracker'
      path: '/oi-tracker'
      fullPath: '/oi-tracker'
      preLoaderRoute: typeof OiTrackerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/execution': {
      id: '/execution'
      path: '/execution'
      fullPath: '/execution'
      preLoaderRoute: typeof ExecutionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backtest': {
      id: '/backtest'
      path: '/backtest'
      fullPath: '/backtest'
      preLoaderRoute: typeof BacktestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BacktestRoute: BacktestRoute,
  DashboardRoute: DashboardRoute,
  ExecutionRoute: ExecutionRoute,
  LiveRoute: LiveRoute,
  LoginRoute: LoginRoute,
  OiTrackerRoute: OiTrackerRoute,
  OiVarRoute: OiVarRoute,
  RollingStraddleRoute: RollingStraddleRoute,
  SettingsRoute: SettingsRoute,
  SurvivorRoute: SurvivorRoute,
  WaveRoute: WaveRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
